- name: Demo on variables
  hosts: localhost
  vars:
    URL: sample.com
  tasks:
    - name: Print URL Variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

# value start with  variable , like msg: {{ URL }} then double quotes are need, if it does not start with variable like
  # msg: Hello {{ URL }}, then quotes are not needed.

# first We use all as default for the hosts and secondly we use localhost if you want to run in the local
# while running with hosts: all we use the below command
  # ansible-playbook -i 172.31.41.11, -e ansible_user=centos -e ansible_password=DevOps321 01-variable.yml
    # after executing the above command we get the msg s sample.com

# if you are running by giving the hosts: local host then directly we run with the below command
  #  ansible-playbook 01.variable.yml
  # after executing the above command we get the msg s sample.com


# Now we try to declare the variable under the task level
- name: Demo on variables
  hosts: localhost
  tasks:
    - name: Print URL1 Variable
      ansible.builtin.debug:
        msg: "{{ URL1 }}"
      vars:
        URL1: sample.com
    - name: Print URL2 Variable
      ansible.builtin.debug:
        msg: "{{ URL2 }}"
      vars:
        URL2: sample.com

# Apart from the above 2 approaches we can also declare the variable on the command line. which is something called as
  # variable precedence
  # Here precedence means priority, now if you declare a variable on the play level or task level. The task level
    # variable has high priority compare to play level variable.
- name: Demo on variables
  hosts: localhost
  vars:
    URL3: example.com
    URL4: example.com
  tasks:
    - name: Print URL3 Variable
      ansible.builtin.debug:
        msg: "{{ URL3 }}"
      vars:
        URL3: samples.com
    - name: Print URL4 Variable
      ansible.builtin.debug:
        msg: "{{ URL4 }}"
      vars:
        URL4: samples.com
# Here we have declare a variable in play level with url: example.com and also declare a variable in task level with
  # url: samples.com. Now if i execute this i will get samples.com as output because The task level variable has high
  # priority compare to play level variable.