- name: Demo on Condition
  hosts: localhost
  tasks:
    - name: Print Linux
      ansible.builtin.debug:
        msg: Hello, Linux
      when: os_name == "linux"

    - name: Print Unix
      ansible.builtin.debug:
        msg: Hello, Unix
      when: os_name == "unix"

# Now in the command line if you give  ansible-playbook 03-conditions.yml -e os_name=Linux then it execute only the
  # Linux one and skip the unix because we have provided the condition.