- name: Demo On AWS SSM Parameter Pull
  hosts: localhost
  tasks:
    - name: lookup ssm parameter store in the current region
      debug: msg="{{ lookup('amazon.aws.aws_ssm', 'sample', region='us-east-2' ) }}"

# Here sample is the name of the parameter