- name: Demo On AWS SSM Parameter Pull
  hosts: all
  tasks:
    - name: lookup ssm parameter store in the current region
      debug: msg="{{ lookup('amazon.aws.aws_ssm', 'sample' ) }}"

# Here sample is the name of the parameter