- name: Demo on Filter
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT
# Here uptime help us to show the number of users
# here we are storing the output in the register

    - name: Print No Of Users
      ansible.builtin.debug:
        msg: "{{ ((OUT.stdout | split(','))[1] | split(' '))[2] }}"


# msg: "{{ OUT }}"  --> in output it give all the details

# Now i want only stdout in the output and i need to split them in a list so i cn give these s a message
    #   msg: "{{ OUT.stdout | split(',') }}"   after executing with these statement we get the below output
      # "msg": [
      #   " 17:57:40 up 28 min",        --- index value 0
      #   "  1 user",                   --- index value 1
      #   "  load average: 0.00",
      #   " 0.00",
      #   " 0.00"

# Now if i want to only the 1st value of the list then i can give the bellow one, in list the index start with 0.
    #   msg: "{{ (OUT.stdout | split(','))[1] }}"    after executing with these statement we get the below output
      #  "msg": "  1 user"

# Now if i want to get the output without user string then i can get it with below one,
    #   msg: "{{ ((OUT.stdout | split(','))[1] | split(' '))[2] }}" after executing with these statement we get the below output
      #  "msg": "1"

# After executing we got the output and in the "stdout": " 17:50:50 up 21 min,  1 user,  load average: 0.08, 0.02, 0.01",
# all these details are in line now i want to split and make them in line
