- name: Demo on Filter
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT
# Here uptime help us to show the number of users
# here we are storing the output in the register

    - name: Print No Of Users
      ansible.builtin.debug:
        msg: "{{ OUT }}"
